# Generated by Django 4.1.5 on 2023-02-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('correct_option', models.TextField(blank=True, null=True)),
                ('incorrect_option1', models.TextField(blank=True, null=True)),
                ('topic', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
