# Generated by Django 4.1.5 on 2023-02-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='incorrect_option2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='incorrect_option3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='incorrect_option4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
