# Generated by Django 4.1.6 on 2023-02-05 23:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('difficulty', models.TextField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('incorrect_answers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=3)),
            ],
        ),
    ]
