# Generated by Django 4.1.6 on 2023-02-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_correct_answer_triviaquestionresult_result_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestionresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.triviaexam'),
        ),
    ]
